CREATE TABLE IF NOT EXISTS Application_Exception_Log (
    AEL_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    AEL_Source VARCHAR(255) NOT NULL,
    AEL_Exception_Type VARCHAR(255) NOT NULL,
    AEL_Message TEXT NOT NULL,
    AEL_Created_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (AEL_ID),
    INDEX idx_AEL_Created_At (AEL_Created_At)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;